// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVtM-v1afp7_rMmxFFrxiDM58PR1ovCbI',
    appId: '1:74113112656:web:09217d1fb3d836b76b0f55',
    messagingSenderId: '74113112656',
    projectId: 'localizarte-752d0',
    authDomain: 'localizarte-752d0.firebaseapp.com',
    storageBucket: 'localizarte-752d0.appspot.com',
    measurementId: 'G-2XHX4EJB22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaz-ETU2lwUdQQeKlW8nDSeNARMqqrLyI',
    appId: '1:74113112656:android:2a213d821f3bbf4c6b0f55',
    messagingSenderId: '74113112656',
    projectId: 'localizarte-752d0',
    storageBucket: 'localizarte-752d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf4SZPIia-wpRwKknkIWfud4cJs-N5jNM',
    appId: '1:74113112656:ios:c612ea4e8d93d9c16b0f55',
    messagingSenderId: '74113112656',
    projectId: 'localizarte-752d0',
    storageBucket: 'localizarte-752d0.appspot.com',
    androidClientId:
        '74113112656-9brnan3v1kckjgqni1q74q03vdmmbp74.apps.googleusercontent.com',
    iosClientId:
        '74113112656-7g7p27cs1t8nrh9l0o4u9kk2enqst654.apps.googleusercontent.com',
    iosBundleId: 'es.uva.gsic.chest',
  );
}
